/** Development retry metadata mirrors the explicit runtime loader registry. */
export const labEntryPaths = {
  'external-memory': 'external-memory/ExternalMemoryLab.tsx',
  'embodied-calculation': 'embodied-calculation/EmbodiedCalculationLab.tsx',
  'executable-rules': 'executable-rules/ExecutableRulesLab.tsx',
  'computation-limits': 'computation-limits/ComputationLimitsLab.tsx',
  'judgment-criteria': 'judgment-criteria/JudgmentCriteriaLab.tsx',
  'linear-separator': 'linear-separator/LinearSeparatorLab.tsx',
  'knowledge-bottleneck': 'knowledge-bottleneck/KnowledgeBottleneckLab.tsx',
  'gradient-descent': 'gradient-descent/GradientDescentLab.tsx',
  convolution: 'convolution/ConvolutionLab.tsx',
  attention: 'attention/AttentionLab.tsx',
  'agent-trace': 'agent-trace/AgentTraceLab.tsx',
  'agi-definitions': 'agi-definitions/AgiDefinitionsLab.tsx',
  'message-budget': 'message-budget/MessageBudgetLab.tsx',
  'ambiguous-code': 'ambiguous-code/AmbiguousCodeLab.tsx',
  'morse-spacing': 'morse-spacing/MorseSpacingLab.tsx',
  'cable-route': 'cable-route/CableRouteLab.tsx',
  'pulse-channel': 'pulse-channel/PulseChannelLab.tsx',
  'binary-noise': 'binary-noise/BinaryNoiseLab.tsx',
  'source-entropy': 'source-entropy/SourceEntropyLab.tsx',
  'huffman-message': 'huffman-message/HuffmanMessageLab.tsx',
  'repetition-channel': 'repetition-channel/RepetitionChannelLab.tsx',
  'secded-inspector': 'secded-inspector/SecdedInspectorLab.tsx',
  'channel-budget': 'channel-budget/ChannelBudgetLab.tsx',
  'message-meaning': 'message-meaning/MessageMeaningLab.tsx',
} as const;
