import type { StoryAct, StoryScene } from '../../types';
import { historyOfAiIllustrations } from './assets';
import { blocks, technicalBlocks } from './act-1';

const fallback = (vi: string, en: string) => ({ diagramLabel: { vi: 'Sơ đồ minh hoạ có thể đọc bằng chữ', en: 'Text-readable illustrative diagram' }, explanation: { vi, en } });

export const actTwo: StoryAct = {
  id: 'act-2', number: 2, title: { vi: 'Máy biết suy luận?', en: 'Can a machine reason?' },
  question: { vi: 'Nếu một quy trình có thể chạy, phần nào của suy nghĩ có thể thành quy trình?', en: 'If a process can run, which parts of thinking can become process?' },
  consequence: blocks('Khi máy suy luận trở thành một lĩnh vực, tên gọi, quỹ tài trợ và tiêu chuẩn đánh giá bắt đầu định hình điều gì được coi là trí tuệ. Các tranh chấp kỹ thuật cũng là tranh chấp về quyền đặt câu hỏi.', 'Once machine reasoning became a field, names, funding, and evaluation standards began to shape what counted as intelligence. Technical disputes were also disputes over who could set the question.'),
  sceneIds: ['scene-04', 'scene-05', 'scene-06'],
};

export const actTwoScenes = [
  {
    id: 'scene-04', actId: 'act-2', period: { vi: '1930–1950', en: '1930–1950' }, title: { vi: 'Tính toán, thông tin và chiến tranh', en: 'Computation, information, and war' },
    humanStory: blocks('Một lý thuyết về tính toán không tự thành một phòng máy. Thế kỷ XX đưa các ý tưởng hình thức vào những tổ chức điện tử, viễn thông, mật mã và chiến tranh, nơi việc vận hành máy, chuẩn bị băng giấy và phối hợp công việc thường ít xuất hiện trong huyền thoại về “máy”. Tại Bletchley Park, các Wren phụ nữ vận hành Colossus; tư liệu lưu trữ đặt máy trong một tổ chức thời chiến có người, vật liệu và quy trình. Turing mở ra một cách mô tả thủ tục bằng trạng thái, ký hiệu và bước chuyển; lý thuyết truyền tin của Shannon cung cấp một ngôn ngữ khác cho mã hoá, nhiễu và độ tin cậy. Cả hai không xóa bối cảnh sử dụng. Một máy có thể thực hiện quy tắc rất chính xác trong khi các mục tiêu quân sự và quyết định tổ chức vẫn nằm ngoài sơ đồ. Lab cho thấy một chương trình dừng và một chương trình tiếp tục trong giới hạn 24 bước. Nó không, và không thể, giải bài toán dừng tổng quát.', 'A theory of computation does not automatically become a machine room. The twentieth century placed formal ideas inside electronic, communications, cryptanalytic, and wartime organizations, where operating a machine, preparing paper tape, and coordinating work are often missing from myths about “the machine.” At Bletchley Park, women Wrens operated Colossus; archival material puts the machine inside a wartime organization of people, materials, and procedures. Turing offers a way to describe procedure through states, symbols, and transitions; Shannon’s communication theory offers another language for encoding, noise, and reliability. Neither removes context of use. A machine can execute a rule precisely while military purposes and organizational decisions remain outside a diagram. The lab shows one program that halts and one that continues within a 24-step bound. It does not, and cannot, solve the general Halting Problem.'),
    technicalHinge: technicalBlocks('Máy Turing tối giản giữ một tape hữu hạn để quan sát, một đầu đọc/ghi và bảng chuyển trạng thái. Mỗi bước sửa một ô, di chuyển một vị trí và chọn trạng thái tiếp theo. Khi không còn luật hoặc gặp halt, lần chạy kết thúc; khi hết maxSteps, lab chỉ báo giới hạn quan sát. Vì có vô số chương trình và đầu vào, kết quả của hai ví dụ không thể được nâng thành chứng minh chung về mọi chương trình.', 'A minimal Turing machine keeps a finite observed tape, a read/write head, and a transition table. Each step changes one cell, moves one position, and selects a next state. When no rule remains or halt is reached, the run ends; when maxSteps is reached, the lab reports an observation limit only. Because programs and inputs are unbounded, two examples cannot become a general proof about every program.'),
    illustration: historyOfAiIllustrations['scene-04'], lab: { kind: 'computation-limits', title: { vi: 'Một lần chạy có giới hạn', en: 'One bounded run' }, instruction: { vi: 'Bước qua hai chương trình, rồi đọc chính xác điều lab biết.', en: 'Step through two programs, then read exactly what the lab knows.' }, config: { tape: '0', startState: 'scan', maxSteps: 24, program: { scan: { write: '1', move: 1, next: 'halt' }, halt: { write: '1', move: 1, next: 'halt' }, loop: { write: '1', move: 1, next: 'loop' } }, cases: [{ id: 'halts', label: { vi: 'Ví dụ dừng', en: 'Halting example' }, tape: '0', startState: 'scan', program: { scan: { write: '1', move: 1, next: 'halt' } } as Record<string, { write: string; move: -1 | 1; next: string }> }, { id: 'continues', label: { vi: 'Ví dụ tiếp tục', en: 'Continuing bounded example' }, tape: '0', startState: 'loop', program: { loop: { write: '1', move: 1, next: 'loop' } } as Record<string, { write: string; move: -1 | 1; next: string }> }] } }, labFallback: fallback('Một run dừng sau một bước; run khác bị giới hạn sau 24 bước.', 'One run halts after one step; another reaches the 24-step observation limit.'), sourceIds: ['turing-1950', 'ieee-shannon', 'uk-national-archives-colossus', 'chm-colossus'], openQuestion: { vi: 'Khi một hệ thống có thể chạy, ai quyết định mục tiêu mà nó phục vụ?', en: 'When a system can run, who decides the purpose it serves?' },
  },
  {
    id: 'scene-05', actId: 'act-2', period: { vi: '1950', en: '1950' }, title: { vi: 'Turing và phép thử bằng hội thoại', en: 'Turing and judgment through conversation' },
    humanStory: blocks('Bài viết năm 1950 của Turing không trao cho thế giới một chiếc máy đo trí tuệ phổ quát. Nó đề xuất đổi một câu hỏi mơ hồ—“máy có thể nghĩ không?”—thành một trò chơi bắt chước bằng hội thoại. Đổi câu hỏi là một lựa chọn phương pháp: nó chuyển chú ý sang hành vi quan sát được, người đánh giá, giao diện ngôn ngữ và điều kiện của một phán đoán. Nhưng cùng một transcript có thể trông nhất quán với người này, thuyết phục với người khác, hoặc chứa đủ kiến thức mà vẫn không cho phép kết luận về hiểu biết. Lab cố ý tách bốn tiêu chí: nhất quán, kiến thức, tự báo cáo và thuyết phục. Người đọc chọn chúng, rồi nhận các finding viết sẵn; không có tổng điểm và không có nhãn “người thắng”. Nhờ vậy, điều thay đổi trong lab là chuẩn phán đoán của chúng ta, không phải bản chất của người đối thoại trên giấy.', 'Turing’s 1950 paper did not hand the world a universal intelligence meter. It proposes replacing a vague question—can machines think?—with an imitation game conducted through conversation. Replacing the question is a methodological choice: it shifts attention to observable behavior, evaluators, language interfaces, and conditions of judgment. Yet the same transcript may seem consistent to one reader, persuasive to another, or knowledgeable enough while still not warranting a conclusion about understanding. That gap matters whenever institutions use conversational performance as evidence. The lab deliberately separates four criteria: consistency, knowledge, self-report, and persuasion. Readers choose them and receive authored findings; there is no aggregate score and no winner label. What changes in the lab is our standard of judgment, not the essence of a respondent on paper.'),
    technicalHinge: technicalBlocks('Một tiêu chí đánh giá là hàm chọn lọc bằng chứng, không phải bản thân bằng chứng. Transcript cố định giữ nội dung không đổi để ta thấy lựa chọn tiêu chí làm đổi kết luận. Lab chỉ trả các finding gắn với tiêu chí được chọn và giữ thứ tự đã viết, nhờ đó không mô phỏng “đọc tâm trí”. Tự báo cáo có thể là dữ liệu về phát ngôn; nó không tự xác nhận trải nghiệm hay năng lực tổng quát.', 'An evaluation criterion is a way to select evidence, not evidence itself. A fixed transcript holds content still so a change in criteria can change a conclusion. The lab returns only authored findings tied to selected criteria and preserves their written order, so it does not simulate mind-reading. Self-report can be evidence about an utterance; it does not by itself verify experience or general capability.'),
    illustration: historyOfAiIllustrations['scene-05'], lab: { kind: 'judgment-criteria', title: { vi: 'Cùng transcript, khác chuẩn', en: 'Same transcript, different criteria' }, instruction: { vi: 'Chọn các tiêu chí bạn muốn dùng để đọc cuộc hội thoại.', en: 'Choose the criteria you want to use when reading the exchange.' }, config: { transcript: { vi: [{ speaker: 'judge', text: 'Bạn có thể giải thích lựa chọn của mình không?' }, { speaker: 'respondent', text: 'Tôi có thể nêu lý do, nhưng lý do đó vẫn cần được kiểm tra.' }], en: [{ speaker: 'judge', text: 'Can you explain your choice?' }, { speaker: 'respondent', text: 'I can state reasons, but those reasons still need checking.' }] }, criteria: [{ id: 'consistency', label: { vi: 'Nhất quán', en: 'Consistency' }, finding: { vi: 'Câu trả lời không tự mâu thuẫn trong đoạn trích ngắn.', en: 'The answer does not contradict itself in this short extract.' } }, { id: 'knowledge', label: { vi: 'Kiến thức', en: 'Knowledge' }, finding: { vi: 'Đoạn trích không đủ để xác nhận phạm vi kiến thức.', en: 'The extract is insufficient to establish knowledge scope.' } }, { id: 'self-report', label: { vi: 'Tự báo cáo', en: 'Self-report' }, finding: { vi: 'Việc nêu lý do là phát ngôn, không phải bằng chứng về trải nghiệm.', en: 'Stating reasons is an utterance, not evidence of experience.' } }, { id: 'persuasion', label: { vi: 'Thuyết phục', en: 'Persuasion' }, finding: { vi: 'Tính thuyết phục phụ thuộc vào người đọc và hoàn cảnh.', en: 'Persuasiveness depends on reader and circumstance.' } }] } }, labFallback: fallback('Bốn tiêu chí cho bốn finding không cộng thành một chứng chỉ trí tuệ.', 'Four criteria produce four findings; they do not add up to an intelligence certificate.'), sourceIds: ['turing-1950', 'nist-ai'], openQuestion: { vi: 'Ai chọn tiêu chí trước khi một cuộc hội thoại bị coi là bằng chứng?', en: 'Who chooses the criteria before a conversation is treated as evidence?' },
  },
  {
    id: 'scene-06', actId: 'act-2', period: { vi: '1955–1958', en: '1955–1958' }, title: { vi: 'Dartmouth, symbolic AI và perceptron', en: 'Dartmouth, symbolic AI, and the perceptron' },
    humanStory: blocks('Đề xuất Dartmouth năm 1955 đặt tên cho một dự án nghiên cứu, mời người tham gia, mô tả ngân sách và trình bày một giả thuyết táo bạo về việc mô tả học tập hay trí tuệ đủ chính xác để máy mô phỏng. Nó không phải khoảnh khắc một lĩnh vực bỗng xuất hiện hoàn chỉnh. Trong cùng không gian lịch sử, các nhà nghiên cứu theo đuổi luật, ngôn ngữ, mạng nơ-ron và học từ ví dụ. Rosenblatt giới thiệu perceptron như một mô hình xác suất cho tổ chức thông tin; cách tiếp cận ấy không đơn giản “thay thế” ký hiệu. Hai truyền thống gặp nhau trong câu hỏi về biểu diễn, dữ liệu và giới hạn. Lab để người đọc kéo một đường phân tách qua các điểm, sau đó bật XOR. Khi không một đường thẳng nào phân loại hoàn hảo, đó là giới hạn của mô hình tuyến tính một lớp trong ví dụ này, không phải bản án cho toàn bộ học máy.', 'The Dartmouth proposal of 1955 named a research project, invited participants, described a budget, and stated a bold conjecture that learning or intelligence might be described precisely enough for a machine to simulate it. It was not a moment when a field suddenly arrived complete. In the same historical space, researchers pursued rules, language, neural nets, and learning from examples. Rosenblatt introduced the perceptron as a probabilistic model for information organization; that approach did not simply “replace” symbols. The traditions meet in questions of representation, data, and limitation. The lab lets readers drag a separating line across points, then enable XOR. When no single line classifies it perfectly, that is a limit of a one-layer linear model in this example, not a verdict on all machine learning.'),
    technicalHinge: technicalBlocks('Bộ phân loại tuyến tính gán nhãn bằng dấu của một biểu thức tuyến tính theo toạ độ, góc và offset. Các điểm separable có thể được chia bởi một đường; XOR đặt các nhãn chéo nhau nên không thể giải bằng một đường duy nhất. Perceptron có lịch sử và biến thể rộng hơn lab. Mục đích tương tác là phân biệt một giới hạn quan sát được của biểu diễn với một tuyên bố quá mức về “AI không thể”.', 'A linear classifier assigns a label by the sign of a linear expression over coordinates, angle, and offset. Separable points can be divided by a line; XOR places labels diagonally so one line cannot solve it. The perceptron has a broader history and many variants beyond the lab. The interaction distinguishes an observable representational limit from an excessive claim that “AI cannot.”'),
    illustration: historyOfAiIllustrations['scene-06'], lab: { kind: 'linear-separator', title: { vi: 'Đường và giới hạn XOR', en: 'A line and XOR’s limit' }, instruction: { vi: 'Kéo đường phân tách, rồi bật các điểm XOR.', en: 'Move the separator, then enable the XOR points.' }, config: { points: [{ id: 'left', x: -1, y: 0, label: -1 }, { id: 'right', x: 1, y: 0, label: 1 }, { id: 'upper', x: 1, y: 1, label: 1 }, { id: 'lower', x: -1, y: -1, label: -1 }, { id: 'xor-00', x: 0, y: 0, label: -1 }, { id: 'xor-01', x: 0, y: 1, label: 1 }, { id: 'xor-10', x: 1, y: 0, label: 1 }, { id: 'xor-11', x: 1, y: 1, label: -1 }], angle: 0, offset: 0 } }, labFallback: fallback('Một đường tách bộ điểm đầu; bốn điểm XOR minh hoạ giới hạn tuyến tính một lớp.', 'One line separates the initial points; four XOR points illustrate a one-layer linear limit.'), sourceIds: ['dartmouth-1955', 'rosenblatt-1958'], openQuestion: { vi: 'Khi một lĩnh vực được đặt tên, ai và cách tiếp cận nào dễ nhận vốn hơn?', en: 'When a field is named, whose approach becomes easier to fund?' },
  },
] satisfies StoryScene[];
