import type { SourceEntry } from '../../types';

const accessedAt = '2026-09-04';
const source = (id: string, kind: SourceEntry['kind'], title: string, authorsOrInstitution: string, year: string, url: string, claimVi: string, claimEn: string): SourceEntry => ({
  id, kind, title, authorsOrInstitution, year, url, accessedAt,
  note: { vi: claimVi, en: claimEn },
});

export const historyOfAiSources: SourceEntry[] = [
  source('met-writing', 'archive', 'The Origins of Writing', 'The Metropolitan Museum of Art', '2004', 'https://www.metmuseum.org/essays/the-origins-of-writing', 'Bảng đất sét và ghi chép hành chính ở Uruk; không coi đây là khởi đầu duy nhất của chữ viết.', 'Clay records and administration at Uruk, without treating this as writing’s single origin.'),
  source('british-cuneiform', 'archive', 'How to write cuneiform', 'British Museum', '2024', 'https://www.britishmuseum.org/blog/how-write-cuneiform', 'Cách dấu nêm được tạo bằng bút trâm; dùng thận trọng vì trang công khai chặn truy cập tự động.', 'How wedge marks are made with a stylus; used cautiously because the public page blocked automated access.'),
  source('smithsonian-abacus', 'artifact', 'The Abacus, the Numeral Frame, and Counters', 'Smithsonian National Museum of American History', 'n.d.', 'https://americanhistory.si.edu/collections/object-groups/the-abacus-the-numeral-frame-and-counters', 'Bàn tính và khung số như vật thể tính toán; trang đã timeout khi kiểm tra.', 'Abaci and numeral frames as calculating objects; the page timed out during verification.'),
  source('chm-abacus', 'archive', 'The Versatile, Venerable Abacus', 'Computer History Museum', 'n.d.', 'https://www.computerhistory.org/revolution/calculators/1/1', 'Giá trị số được biểu diễn bằng vị trí hạt và do người vận hành dịch chuyển.', 'Numerical value is represented by bead position and moved by an operator.'),
  source('chm-babbage', 'archive', 'A Brief History', 'Computer History Museum', 'n.d.', 'https://www.computerhistory.org/babbage/history/', 'Babbage, thợ cơ khí, vốn nhà nước và những ràng buộc vật chất của Difference/Analytical Engine.', 'Babbage, toolmakers, state funding, and the material constraints of the Difference and Analytical Engines.'),
  source('chm-ada', 'archive', 'Ada Lovelace', 'Computer History Museum', 'n.d.', 'https://www.computerhistory.org/babbage/adalovelace', 'Ghi chú năm 1843 của Lovelace mô tả một thủ tục giải toán và khả năng thao tác ký hiệu.', 'Lovelace’s 1843 notes describe a mathematical procedure and the possibility of symbolic manipulation.'),
  source('turing-1950', 'paper', 'Computing Machinery and Intelligence', 'Alan Turing, King’s College London archive', '1950', 'https://turingarchive.kings.cam.ac.uk/publications-lectures-and-talks-amtb/amt-b-9', 'Bài viết đặt lại câu hỏi về máy và trí tuệ qua trò chơi bắt chước.', 'The paper reframes the question of machines and intelligence through the imitation game.'),
  source('ieee-shannon', 'paper', 'A Mathematical Theory of Communication', 'Claude Shannon / IEEE Reach', '1948', 'https://reach.ieee.org/primary-sources/a-mathematical-theory-of-communication/', 'Lý thuyết truyền tin cung cấp ngôn ngữ cho tín hiệu, nhiễu và mã hoá.', 'Communication theory supplies a language for signal, noise, and encoding.'),
  source('dartmouth-1955', 'archive', 'A Proposal for the Dartmouth Summer Research Project on Artificial Intelligence', 'John McCarthy, Marvin Minsky, Nathaniel Rochester, Claude Shannon', '1955', 'https://www-formal.stanford.edu/jmc/history/dartmouth/dartmouth.html', 'Bản đề xuất đặt tên AI, nêu tham vọng nghiên cứu và phác lộ ngân sách/tổ chức.', 'The proposal names AI, states research ambitions, and exposes its funding and institutional frame.'),
  source('rosenblatt-1958', 'paper', 'The Perceptron: A Probabilistic Model for Information Storage and Organization in the Brain', 'Frank Rosenblatt', '1958', 'https://homepages.math.uic.edu/~lreyzin/papers/rosenblatt58.pdf', 'Một mô hình perceptron sớm cho việc học từ ví dụ; không phải toàn bộ lịch sử mạng nơ-ron.', 'An early perceptron model for learning from examples, not the whole history of neural networks.'),
  source('chm-feigenbaum', 'archive', 'Edward Feigenbaum', 'Computer History Museum', 'n.d.', 'https://computerhistory.org/profile/edward-feigenbaum/', 'Bối cảnh phát triển hệ chuyên gia và vai trò của tri thức miền hẹp.', 'Context for expert systems and the role of narrow domain knowledge.'),
  source('chm-expert-systems', 'archive', 'Expert Systems oral-history materials', 'Computer History Museum', '1980s', 'https://archive.computerhistory.org/resources/access/text/2018/03/102738236-05-01-acc.pdf', 'Tư liệu về kỹ thuật tri thức, triển khai và chi phí duy trì hệ chuyên gia.', 'Material on knowledge engineering, deployment, and maintenance costs in expert systems.'),
  source('backprop-1986', 'paper', 'Learning representations by back-propagating errors', 'Rumelhart, Hinton, Williams', '1986', 'https://www.nature.com/articles/323533a0', 'Lan truyền ngược phân bổ tín hiệu sai số qua các lớp để điều chỉnh trọng số.', 'Back-propagation distributes error signals through layers to adjust weights.'),
  source('imagenet-2009', 'paper', 'ImageNet: A Large-Scale Hierarchical Image Database', 'Jia Deng and colleagues', '2009', 'https://www.image-net.org/static_files/papers/imagenet_cvpr09.pdf', 'ImageNet như một bộ dữ liệu phân cấp quy mô lớn, phụ thuộc vào tổ chức nhãn.', 'ImageNet as a large hierarchical dataset dependent on organized labeling.'),
  source('alexnet-2012', 'paper', 'ImageNet Classification with Deep Convolutional Neural Networks', 'Alex Krizhevsky, Ilya Sutskever, Geoffrey Hinton', '2012', 'https://papers.nips.cc/paper_files/paper/2012/hash/c399862d3b9d6b76c8436e924a68c45b-Abstract.html', 'Mạng tích chập sâu đạt kết quả benchmark ImageNet, với kiến trúc và hạ tầng tính toán là điều kiện.', 'A deep convolutional network reached ImageNet benchmark results through architecture and computing infrastructure.'),
  source('transformer-2017', 'paper', 'Attention Is All You Need', 'Ashish Vaswani and colleagues', '2017', 'https://arxiv.org/abs/1706.03762', 'Transformer dựa trên attention thay cho recurrence/convolution trong mô hình dịch được mô tả.', 'The described Transformer relies on attention instead of recurrence or convolution for translation.'),
  source('instructgpt-2022', 'paper', 'Training language models to follow instructions with human feedback', 'Long Ouyang and colleagues', '2022', 'https://arxiv.org/abs/2203.02155', 'Dữ liệu hướng dẫn, xếp hạng của người gán nhãn và RLHF là các bước riêng.', 'Instruction data, labeler rankings, and RLHF are distinct steps.'),
  source('react-2022', 'paper', 'ReAct: Synergizing Reasoning and Acting in Language Models', 'Shunyu Yao and colleagues', '2022', 'https://arxiv.org/abs/2210.03629', 'Trace lý luận–hành động có thể xen kẽ và giao tiếp với nguồn bên ngoài; không tự cấp quyền.', 'Reasoning–action traces can interleave and interface with outside sources; they do not grant permission by themselves.'),
  source('ai-index-2026', 'report', 'The 2026 AI Index Report', 'Stanford Institute for Human-Centered AI', '2026', 'https://hai.stanford.edu/ai-index/2026-ai-index-report', 'Báo cáo theo dõi năng lực, hạ tầng, kinh tế, quản trị và những khoảng trống đo lường.', 'The report tracks capability, infrastructure, economy, governance, and measurement gaps.'),
  source('stanford-agi', 'report', 'What Is AGI?', 'Stanford Institute for Human-Centered AI', '2026', 'https://hai.stanford.edu/ai-definitions/what-is-agi-artificial-general-intelligence', 'AGI là thuật ngữ đang tranh luận, với các định nghĩa và ngưỡng khác nhau.', 'AGI is a contested term with differing definitions and thresholds.'),
  source('nist-ai', 'report', 'Artificial intelligence', 'NIST Computer Security Resource Center', '2025', 'https://csrc.nist.gov/glossary/term/artificial_intelligence', 'Định nghĩa thuật ngữ AI dùng để phân biệt mô tả kỹ thuật với tuyên bố xã hội rộng hơn.', 'An AI glossary definition used to distinguish technical description from broader social claims.'),
];
